export function TreeAttrs() {
  return {
    isDataModel: false,
    defaultExpandAll: true,
    expandOnClickNode: true,
    filter: false,
    showCheckbox: false,
    accordion: false,
    lazy: false,
    width: "200",
    nodeKey: "",
    propsLabel: "",
    propsChildren: "",
    dataTransitionFn: "",
    filterFn: "",
    loadFn: "",
    nodeClick: "",
    dataTransitionParentField: "",
    dataTransitionCurField: "",
    renderContent: "",
    requestUrl: "",
    requestType: "",
    requestParamsConfig: {},
    treeSql: "",
    treeOrderExpr: "",
    style: "",
    deliveryField: "",
    defaultCheckedKeys: "",
    defaultExpandedKeys: "",
    currentNodeKey: "",
    iconClass: ""
  };
}
