/* Automatically generated by './build/bin/build-entry.js' */

import baseRenderFrom from '../packages/BaseRenderForm/main.js';
import baseRenderTable from '../packages/BaseRenderTable/main.js';
import BaseRenderRegular from '../packages/BaseRenderRegular/main.js';
import completeTable from '../packages/completeTable/main.js';
import setupTable from '../packages/setupTable/main.js';

const components = [
  baseRenderFrom,
  baseRenderTable,
  BaseRenderRegular,
  completeTable,
  setupTable,
];

const install = function(Vue) {
  components.forEach((component) => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  baseRenderFrom,
  baseRenderTable,
  BaseRenderRegular,
  completeTable,
  setupTable,
};
